# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_3.ui'
#
# Created: Thu Feb 28 14:18:32 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(900, 358)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 1, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_12 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 3, 3, 1, 1)
        self.temperatura_lcd = QtGui.QLCDNumber(Dialog)
        self.temperatura_lcd.setFrameShape(QtGui.QFrame.NoFrame)
        self.temperatura_lcd.setFrameShadow(QtGui.QFrame.Plain)
        self.temperatura_lcd.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.temperatura_lcd.setProperty("intValue", 32)
        self.temperatura_lcd.setObjectName(_fromUtf8("temperatura_lcd"))
        self.gridLayout.addWidget(self.temperatura_lcd, 6, 1, 1, 1)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 5, 0, 1, 8)
        self.temperatura_set = QtGui.QDoubleSpinBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.temperatura_set.setFont(font)
        self.temperatura_set.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatura_set.setReadOnly(False)
        self.temperatura_set.setDecimals(1)
        self.temperatura_set.setMaximum(50.0)
        self.temperatura_set.setSingleStep(0.5)
        self.temperatura_set.setObjectName(_fromUtf8("temperatura_set"))
        self.gridLayout.addWidget(self.temperatura_set, 6, 3, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 6, 1, 2)
        self.apaga_llum_2 = QtGui.QPushButton(Dialog)
        self.apaga_llum_2.setObjectName(_fromUtf8("apaga_llum_2"))
        self.gridLayout.addWidget(self.apaga_llum_2, 4, 4, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_10 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.temperatura_estat_funcionament = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.temperatura_estat_funcionament.setFont(font)
        self.temperatura_estat_funcionament.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatura_estat_funcionament.setReadOnly(True)
        self.temperatura_estat_funcionament.setObjectName(_fromUtf8("temperatura_estat_funcionament"))
        self.horizontalLayout.addWidget(self.temperatura_estat_funcionament)
        self.temperatura_apaga = QtGui.QPushButton(Dialog)
        self.temperatura_apaga.setObjectName(_fromUtf8("temperatura_apaga"))
        self.horizontalLayout.addWidget(self.temperatura_apaga)
        self.temperatura_encendre = QtGui.QPushButton(Dialog)
        self.temperatura_encendre.setObjectName(_fromUtf8("temperatura_encendre"))
        self.horizontalLayout.addWidget(self.temperatura_encendre)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 4, 1, 4)
        self.label_13 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 3, 6, 1, 1)
        self.label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 8)
        self.line_4 = QtGui.QFrame(Dialog)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 2, 5, 3, 1)
        self.label_11 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.apaga_llum_1 = QtGui.QPushButton(Dialog)
        self.apaga_llum_1.setObjectName(_fromUtf8("apaga_llum_1"))
        self.gridLayout.addWidget(self.apaga_llum_1, 4, 1, 1, 1)
        self.label_9 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.estat_llum_3 = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.estat_llum_3.setFont(font)
        self.estat_llum_3.setAlignment(QtCore.Qt.AlignCenter)
        self.estat_llum_3.setReadOnly(True)
        self.estat_llum_3.setObjectName(_fromUtf8("estat_llum_3"))
        self.gridLayout.addWidget(self.estat_llum_3, 3, 7, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.encendre_llum_1 = QtGui.QPushButton(Dialog)
        self.encendre_llum_1.setObjectName(_fromUtf8("encendre_llum_1"))
        self.gridLayout.addWidget(self.encendre_llum_1, 4, 0, 1, 1)
        self.estat_llum_1 = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.estat_llum_1.setFont(font)
        self.estat_llum_1.setAlignment(QtCore.Qt.AlignCenter)
        self.estat_llum_1.setReadOnly(True)
        self.estat_llum_1.setObjectName(_fromUtf8("estat_llum_1"))
        self.gridLayout.addWidget(self.estat_llum_1, 3, 1, 1, 1)
        self.estat_llum_2 = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.estat_llum_2.setFont(font)
        self.estat_llum_2.setAlignment(QtCore.Qt.AlignCenter)
        self.estat_llum_2.setReadOnly(True)
        self.estat_llum_2.setObjectName(_fromUtf8("estat_llum_2"))
        self.gridLayout.addWidget(self.estat_llum_2, 3, 4, 1, 1)
        self.encendre_llum_2 = QtGui.QPushButton(Dialog)
        self.encendre_llum_2.setObjectName(_fromUtf8("encendre_llum_2"))
        self.gridLayout.addWidget(self.encendre_llum_2, 4, 3, 1, 1)
        self.apaga_llum_3 = QtGui.QPushButton(Dialog)
        self.apaga_llum_3.setObjectName(_fromUtf8("apaga_llum_3"))
        self.gridLayout.addWidget(self.apaga_llum_3, 4, 7, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 3, 1, 2)
        self.encendre_llum_3 = QtGui.QPushButton(Dialog)
        self.encendre_llum_3.setObjectName(_fromUtf8("encendre_llum_3"))
        self.gridLayout.addWidget(self.encendre_llum_3, 4, 6, 1, 1)
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 2, 2, 3, 1)
        self.line_5 = QtGui.QFrame(Dialog)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout.addWidget(self.line_5, 1, 0, 1, 8)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.apaga_llum_1, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.apagar_llum_1)
        QtCore.QObject.connect(self.apaga_llum_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.apagar_llum_2)
        QtCore.QObject.connect(self.apaga_llum_3, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.apagar_llum_3)
        QtCore.QObject.connect(self.encendre_llum_1, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.encendre_l_1)
        QtCore.QObject.connect(self.encendre_llum_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.encendre_l_2)
        QtCore.QObject.connect(self.encendre_llum_3, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.encendre_l_3)
        QtCore.QObject.connect(self.temperatura_set, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Dialog.set_calefacio)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Estat Llum 2:                  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Llum 3", None, QtGui.QApplication.UnicodeUTF8))
        self.apaga_llum_2.setText(QtGui.QApplication.translate("Dialog", "Apaga", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Estat:", None, QtGui.QApplication.UnicodeUTF8))
        self.temperatura_estat_funcionament.setText(QtGui.QApplication.translate("Dialog", "En marxa", None, QtGui.QApplication.UnicodeUTF8))
        self.temperatura_apaga.setText(QtGui.QApplication.translate("Dialog", "Apaga", None, QtGui.QApplication.UnicodeUTF8))
        self.temperatura_encendre.setText(QtGui.QApplication.translate("Dialog", "Encendre", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Estat Llum 3:                 ", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Complex nº 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Estat Llum 1:               ", None, QtGui.QApplication.UnicodeUTF8))
        self.apaga_llum_1.setText(QtGui.QApplication.translate("Dialog", "Apaga", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Temperatura:", None, QtGui.QApplication.UnicodeUTF8))
        self.estat_llum_3.setText(QtGui.QApplication.translate("Dialog", "Apagat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "LLum 1", None, QtGui.QApplication.UnicodeUTF8))
        self.encendre_llum_1.setText(QtGui.QApplication.translate("Dialog", "Encendre", None, QtGui.QApplication.UnicodeUTF8))
        self.estat_llum_1.setText(QtGui.QApplication.translate("Dialog", "Ences", None, QtGui.QApplication.UnicodeUTF8))
        self.estat_llum_2.setText(QtGui.QApplication.translate("Dialog", "Apagat", None, QtGui.QApplication.UnicodeUTF8))
        self.encendre_llum_2.setText(QtGui.QApplication.translate("Dialog", "Encendre ", None, QtGui.QApplication.UnicodeUTF8))
        self.apaga_llum_3.setText(QtGui.QApplication.translate("Dialog", "Apaga", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Llum 2", None, QtGui.QApplication.UnicodeUTF8))
        self.encendre_llum_3.setText(QtGui.QApplication.translate("Dialog", "Encendre", None, QtGui.QApplication.UnicodeUTF8))

