# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Thu Feb 28 14:19:03 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1016, 509)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 0, 3, 4, 1)
        self.complex_1_administra = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.complex_1_administra.setFont(font)
        self.complex_1_administra.setObjectName(_fromUtf8("complex_1_administra"))
        self.gridLayout_3.addWidget(self.complex_1_administra, 3, 0, 1, 3)
        self.complex_2_humitat = QtGui.QLCDNumber(self.centralwidget)
        self.complex_2_humitat.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.complex_2_humitat.setObjectName(_fromUtf8("complex_2_humitat"))
        self.gridLayout_3.addWidget(self.complex_2_humitat, 2, 5, 1, 1)
        self.complex_3_humitat = QtGui.QLCDNumber(self.centralwidget)
        self.complex_3_humitat.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.complex_3_humitat.setObjectName(_fromUtf8("complex_3_humitat"))
        self.gridLayout_3.addWidget(self.complex_3_humitat, 2, 9, 1, 1)
        self.complex_3_administra = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.complex_3_administra.setFont(font)
        self.complex_3_administra.setObjectName(_fromUtf8("complex_3_administra"))
        self.gridLayout_3.addWidget(self.complex_3_administra, 3, 8, 1, 3)
        self.complex_1_temperatura = QtGui.QLCDNumber(self.centralwidget)
        self.complex_1_temperatura.setSmallDecimalPoint(False)
        self.complex_1_temperatura.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.complex_1_temperatura.setObjectName(_fromUtf8("complex_1_temperatura"))
        self.gridLayout_3.addWidget(self.complex_1_temperatura, 2, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_5.addWidget(self.label_19, 0, 0, 1, 1)
        self.altre_creixent_lcd = QtGui.QLCDNumber(self.centralwidget)
        self.altre_creixent_lcd.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.altre_creixent_lcd.setObjectName(_fromUtf8("altre_creixent_lcd"))
        self.gridLayout_5.addWidget(self.altre_creixent_lcd, 0, 1, 1, 1)
        self.altre_creixent_progress_bar = QtGui.QProgressBar(self.centralwidget)
        self.altre_creixent_progress_bar.setProperty("value", 24)
        self.altre_creixent_progress_bar.setObjectName(_fromUtf8("altre_creixent_progress_bar"))
        self.gridLayout_5.addWidget(self.altre_creixent_progress_bar, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 10, 8, 1, 3)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 1, 2, 1, 1)
        self.complex_3_temperaura = QtGui.QLCDNumber(self.centralwidget)
        self.complex_3_temperaura.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.complex_3_temperaura.setObjectName(_fromUtf8("complex_3_temperaura"))
        self.gridLayout_3.addWidget(self.complex_3_temperaura, 2, 8, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_5.addWidget(self.label_20)
        self.aus_creixent_lcd = QtGui.QLCDNumber(self.centralwidget)
        self.aus_creixent_lcd.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.aus_creixent_lcd.setProperty("intValue", 25)
        self.aus_creixent_lcd.setObjectName(_fromUtf8("aus_creixent_lcd"))
        self.horizontalLayout_5.addWidget(self.aus_creixent_lcd)
        self.aus_creixent_progress_bar = QtGui.QProgressBar(self.centralwidget)
        self.aus_creixent_progress_bar.setProperty("value", 24)
        self.aus_creixent_progress_bar.setObjectName(_fromUtf8("aus_creixent_progress_bar"))
        self.horizontalLayout_5.addWidget(self.aus_creixent_progress_bar)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 8, 8, 1, 3)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 7, 0, 1, 11)
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 8, 1, 3)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.aus_totals = QtGui.QLCDNumber(self.centralwidget)
        self.aus_totals.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.aus_totals.setObjectName(_fromUtf8("aus_totals"))
        self.gridLayout_4.addWidget(self.aus_totals, 0, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_4.addWidget(self.label_17, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 8, 0, 1, 3)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 5, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout.addWidget(self.label_18)
        self.altre_adults_lcd = QtGui.QLCDNumber(self.centralwidget)
        self.altre_adults_lcd.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.altre_adults_lcd.setObjectName(_fromUtf8("altre_adults_lcd"))
        self.horizontalLayout.addWidget(self.altre_adults_lcd)
        self.altre_adults_progress_bar = QtGui.QProgressBar(self.centralwidget)
        self.altre_adults_progress_bar.setProperty("value", 24)
        self.altre_adults_progress_bar.setObjectName(_fromUtf8("altre_adults_progress_bar"))
        self.horizontalLayout.addWidget(self.altre_adults_progress_bar)
        self.gridLayout_3.addLayout(self.horizontalLayout, 10, 4, 1, 3)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 1, 10, 1, 1)
        self.complex_2_administra = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.complex_2_administra.setFont(font)
        self.complex_2_administra.setObjectName(_fromUtf8("complex_2_administra"))
        self.gridLayout_3.addWidget(self.complex_2_administra, 3, 4, 1, 3)
        self.complex_1_lluminositat = QtGui.QLCDNumber(self.centralwidget)
        self.complex_1_lluminositat.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.complex_1_lluminositat.setObjectName(_fromUtf8("complex_1_lluminositat"))
        self.gridLayout_3.addWidget(self.complex_1_lluminositat, 2, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 9, 1, 1)
        self.complex_2_lluminositat = QtGui.QLCDNumber(self.centralwidget)
        self.complex_2_lluminositat.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.complex_2_lluminositat.setObjectName(_fromUtf8("complex_2_lluminositat"))
        self.gridLayout_3.addWidget(self.complex_2_lluminositat, 2, 6, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_3.addWidget(self.label_14)
        self.altre_total = QtGui.QLCDNumber(self.centralwidget)
        self.altre_total.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.altre_total.setObjectName(_fromUtf8("altre_total"))
        self.horizontalLayout_3.addWidget(self.altre_total)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 10, 0, 1, 3)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 3)
        self.complex_2_temperatura = QtGui.QLCDNumber(self.centralwidget)
        self.complex_2_temperatura.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.complex_2_temperatura.setObjectName(_fromUtf8("complex_2_temperatura"))
        self.gridLayout_3.addWidget(self.complex_2_temperatura, 2, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.complex_1_humitat = QtGui.QLCDNumber(self.centralwidget)
        self.complex_1_humitat.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.complex_1_humitat.setObjectName(_fromUtf8("complex_1_humitat"))
        self.gridLayout_3.addWidget(self.complex_1_humitat, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 1, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 4, 1, 3)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_3.addWidget(self.line_3, 9, 0, 1, 11)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 1, 1, 1, 1)
        self.complex_3_luminositat = QtGui.QLCDNumber(self.centralwidget)
        self.complex_3_luminositat.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.complex_3_luminositat.setObjectName(_fromUtf8("complex_3_luminositat"))
        self.gridLayout_3.addWidget(self.complex_3_luminositat, 2, 10, 1, 1)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 6, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 1, 8, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_3.addWidget(self.line_2, 0, 7, 4, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_4.addWidget(self.label_15)
        self.aus_adults_lcd = QtGui.QLCDNumber(self.centralwidget)
        self.aus_adults_lcd.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.aus_adults_lcd.setObjectName(_fromUtf8("aus_adults_lcd"))
        self.horizontalLayout_4.addWidget(self.aus_adults_lcd)
        self.aus_adults_progress_bar = QtGui.QProgressBar(self.centralwidget)
        self.aus_adults_progress_bar.setProperty("value", 24)
        self.aus_adults_progress_bar.setObjectName(_fromUtf8("aus_adults_progress_bar"))
        self.horizontalLayout_4.addWidget(self.aus_adults_progress_bar)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 8, 4, 1, 3)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 4, 0, 2, 11)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_3.addWidget(self.line_4, 6, 0, 1, 11)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1016, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAjuda_amb_el_programa = QtGui.QAction(MainWindow)
        self.actionAjuda_amb_el_programa.setObjectName(_fromUtf8("actionAjuda_amb_el_programa"))
        self.actionDetall_sobre_els_animals = QtGui.QAction(MainWindow)
        self.actionDetall_sobre_els_animals.setObjectName(_fromUtf8("actionDetall_sobre_els_animals"))
        self.actionWifi_Farm_v0_1 = QtGui.QAction(MainWindow)
        self.actionWifi_Farm_v0_1.setObjectName(_fromUtf8("actionWifi_Farm_v0_1"))
        self.actionContacta_amb_l_empresa_fabricant = QtGui.QAction(MainWindow)
        self.actionContacta_amb_l_empresa_fabricant.setObjectName(_fromUtf8("actionContacta_amb_l_empresa_fabricant"))
        self.actionConecxio_per_IP = QtGui.QAction(MainWindow)
        self.actionConecxio_per_IP.setObjectName(_fromUtf8("actionConecxio_per_IP"))

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.complex_1_administra, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.administra_complex_1)
        QtCore.QObject.connect(self.complex_2_administra, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.administra_complex_2)
        QtCore.QObject.connect(self.complex_3_administra, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.administra_complex_3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.complex_1_administra.setText(QtGui.QApplication.translate("MainWindow", "Administra Complex nº 1", None, QtGui.QApplication.UnicodeUTF8))
        self.complex_3_administra.setText(QtGui.QApplication.translate("MainWindow", "Administra Complex nº 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "En creixement  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Lluminositat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "En creixement ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Informacio Adicional ", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Complex nº 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Populacio total de Aus ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Humitat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Populacio Adulta   ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Lluminositat", None, QtGui.QApplication.UnicodeUTF8))
        self.complex_2_administra.setText(QtGui.QApplication.translate("MainWindow", "Administra Complex nº 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Humitat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Populacio total de ...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Complex nº 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Temperatura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Temperatura ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Complex nº 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Humitat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Lluminositat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Temperatura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Populacio Adulta   ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAjuda_amb_el_programa.setText(QtGui.QApplication.translate("MainWindow", "Ajuda amb el programa", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDetall_sobre_els_animals.setText(QtGui.QApplication.translate("MainWindow", "Detall sobre els animals", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWifi_Farm_v0_1.setText(QtGui.QApplication.translate("MainWindow", "Wifi_Farm v0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionContacta_amb_l_empresa_fabricant.setText(QtGui.QApplication.translate("MainWindow", "Contacta amb l\'empresa fabricant", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConecxio_per_IP.setText(QtGui.QApplication.translate("MainWindow", "Conecxio per IP", None, QtGui.QApplication.UnicodeUTF8))

